swagger: "2.0"
info:
  version: 1.0.0
  title: COMATCH product development
  description: App to collect product development operational metrics
basePath: /api/v1

tags:
  - name: Specification
    description: The swagger API specification
  - name: Users
    description: Users resource endpoints

consumes:
  - application/json
produces:
  - application/json

definitions:
  errorBody:
    type: object
    properties:
      name:
        type: string
      message:
        type: string
      stack:
        type: string
  createProductDevelopmentRequest:
    type: object
    properties:
      ticketBoardKey:
        type: string
      defaultStart:
        type: string
        format: date
  startTicketUpdateCollectionRequest:
    type: object
    properties:
      productDevId:
        type: string

paths:
  /users:
    get:
      tags:
        - Users
      description: Searches users
      parameters:
        - name: session
          in: path
          required: true
          description: should get current user
          type: boolean
      responses:
        200:
          description: Returns all examples
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  given_name:
                    type: string
                  family_name:
                    type: string
                  picture:
                    type: string
                  locale:
                    type: string
  /users/auth:
    get:
      tags:
        - Users
      description: Authenticate session
      parameters:
        - name: code
          in: path
          required: true
          description: athentication code
          type: string
      responses:
        200:
          description: Returns all examples
        404:
          description: Authentication failed

  /productDevelopments/{id}:
    get:
      tags:
        - ProductDevelopment
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the product development project to retrieve
          type: integer
      responses:
        200:
          description: Return the product development project with the specified id
        404:
          description: Example not found
  /productDevelopments:
    get:
      tags:
        - ProductDevelopment
      parameters:
        - name: ticketBoardKey
          in: query
          description: The ticket board ket to get ticket updates from
          required: true
          type: string
      responses:
        200:
          description: Return the product development project with the specified id
        404:
          description: Example not found
    post:
      summary: Create product development project
      tags:
        - ProductDevelopment
      parameters:
        - name: createProductDevelopmentRequest
          in: body
          description: Create product development project request.
          required: true
          schema:
            $ref: "#/definitions/createProductDevelopmentRequest"
      responses:
        '200':
          description: Created
        '400':
          description: Failed
          content:
            application/json:
              schema:
                $ref: '#/definitions/errorBody'

  /ticketUpdateCollections:
    get:
      summary: Searche ticket update collections
      tags:
        - TicketUpdateCollection
      parameters:
        - name: productDevId
          in: query
          description: Product development project id
          required: true
          type: string
        - name: latest
          in: query
          description: Should return only the latest collection
          required: false
          type: boolean
      responses:
        '200':
          description: Created
        '400':
          description: Failed
          content:
            application/json:
              schema:
                $ref: '#/definitions/errorBody'
    post:
      summary: Start ticket update collection from product development ticket board
      tags:
        - TicketUpdateCollection
      parameters:
        - name: startTicketUpdateCollectionRequestBody
          in: body
          description: Start ticket update collection request.
          required: true
          schema:
            $ref: "#/definitions/startTicketUpdateCollectionRequest"
      responses:
        '200':
          description: Created
        '400':
          description: Failed
          content:
            application/json:
              schema:
                $ref: '#/definitions/errorBody'

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
