version: '3.1'

services:
  db:
    image: postgres
    container_name: postgresql
    #restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initdb.sh:/docker-entrypoint-initdb.d/1-initdb.sh
      - ./db.sql:/docker-entrypoint-initdb.d/2-db.sql
    ports:
      - 5432:5432

  cache:
    image: redis
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  queue:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: jira
      RABBITMQ_DEFAULT_PASS: jira123
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672
